import { DM_Sans, DM_Mono, Caveat } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
    variable: "--font-dm-sans",
    weight: ["400", "700"],
    subsets: ["latin"],
});

const caveat = Caveat({
    variable: "--font-caveat",
    subsets: ["latin"],
});

// const dmMono = DM_Mono({
//   variable: "--font-dm-mono",
//   subsets: ["latin"],
// });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

import SmoothScrolling from "../utilities/SmoothScrolling";

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${dmSans.variable} ${caveat.variable} antialiased`}
            >
                <SmoothScrolling>{children}</SmoothScrolling>
            </body>
        </html>
    );
}
